### ISSUE TITLE
Does not reply to queries for A records

### ISSUE THREAD

**Issue by troglobit** [troglobit/mdnsd#15]
I've tried ping foo.local when mdnsd announces a record with foo.local as target.  Putting it in here mainly for my own bookkeeping.

Blocker for the v0.8 release.

**Comment by fzs** [comment]
Is this still relevant?

**Comment by troglobit** [comment]
Good question, I just tried pinging my embedded system, that runs mdnsd, from my PC and got ping through w/o any problems.  Can't remember what this might've been about, so let's close it, thanks!
