### ISSUE TITLE
Sharing a printer via Bonjour

### ISSUE THREAD

**Issue by MegaZeroX10** [troglobit/mdnsd#24]
How do I use mdnsd to do that?

**Comment by troglobit** [comment]
I'm sure this is not the correct forum for your question. Check with your system och distribution support pages instead.

**Comment by MegaZeroX10** [comment]
Huh?

**Comment by troglobit** [comment]
I'm pretty sure mdnsd isn't in production use in any operating system, except for a select few. You probably want to look at the Apple mDNSResponder project, or the Linux Avahi one.

But if you're really serious, I just pushed a commit with two examples: printer.service and ipp.service.
