### ISSUE TITLE
usage description wrong

### ISSUE THREAD

**Issue by bong1991** [troglobit/mdnsd#3]
Hey,

just a minor wrong printf in the usage description. In line 92 of mdnsd.c it still says mhttp. To get rid of it for all time, you could make
printf("usage: %s 'unique name' 12.34.56.78 80 '/optionalpath'\n", argv[0]);

Best regards

**Comment by troglobit** [comment]
Thanks for pointing it out, I have a backlog of fixes that I need to clean up and apply to this project. I'll see about getting around to finding the time for it soon, I hope.
