### ISSUE TITLE
_ldecomp breaks if on some offsets (128-255, 384-511, etc)

### ISSUE THREAD

**Issue by ChrisBeaumont67** [troglobit/mdnsd#43]
It appears that the signed/unsigned handling in _ldecomp() leaves a few things in limbo... 

Attaching a small code sample that highlights this (exhaustively), with an inline fix (a simple cast does wonders :smile:)

[_ldecomp.zip](https://github.com/troglobit/mdnsd/files/6469755/_ldecomp.zip)

**Comment by troglobit** [comment]
Interesting!  Do you think you could whip up a patch or pull request?

**Comment by ChrisBeaumont67** [comment]
[Sorry for the long delay]
I couldn't manage to actually create a PR !?!?!   resorting to a copy/paste...

`$ git diff master...
diff --git a/libmdnsd/1035.c b/libmdnsd/1035.c
index 9bcb33f..3fe6efc 100644
--- a/libmdnsd/1035.c
+++ b/libmdnsd/1035.c
@@ -86,7 +86,7 @@ static unsigned short int _ldecomp(const char *ptr)
 
        i = 0xc0 ^ ptr[0];
        i <<= 8;
-       i |= ptr[1];
+       i |= (unsigned char)ptr[1];
        if (i >= 4096)
                i = 4095;
`

`$ git log
commit 84d09bafa5949368573b7ef81b66ad2373b5526e (HEAD -> Issue43)
Author: Chris Beaumont <cbeaumont@plume.com>
Date:   Fri May 21 09:05:53 2021 -0700

    Issue43: _ldecomp breaking on long name offsets
    
    Add proper type cast to avoid implicit sign extension.
`

**Comment by troglobit** [comment]
Thank you! I'll have a look at the ZIP later this weekend, I hope.

You have to fork the repo and push to your own fork, then create a pull request.  This because I (and GitHub by default) don't allow anyone to push.

**Comment by troglobit** [comment]
There, sorry for taking so long to apply this to master!
