### ISSUE TITLE
Buildroot support

### ISSUE THREAD

**Issue by tianyuanhao** [troglobit/mdnsd#44]
It seems that there are some Linux distributions that provide the `mdnsd` package.

[![Packaging status](https://repology.org/badge/tiny-repos/mdnsd.svg)](https://repology.org/project/mdnsd/versions)

Will there be an official support for [Buildroot](https://buildroot.org/)?

Here is an example:

```makefile
################################################################################
#
# mdnsd
#
################################################################################

MDNSD_VERSION = 1173d85c288ca6eda187ec2ce1dfe113e005ecdd
MDNSD_SITE = $(call github,troglobit,mdnsd,$(MDNSD_VERSION))
MDNSD_LICENSE = BSD-3-Clause
MDNSD_LICENSE_FILES = LICENSE

MDNSD_AUTORECONF = YES

define MDNSD_REMOVE_EXAMPLES
	$(RM) $(TARGET_DIR)/etc/mdns.d/ssh.service
endef
MDNSD_POST_INSTALL_TARGET_HOOKS += MDNSD_REMOVE_EXAMPLES

$(eval $(autotools-package))
```

**Comment by troglobit** [comment]
Yes, that's the plan at least, unless someone beats me to it :)

For me personally I want to fix #8 first and release v0.11.

**Comment by troglobit** [comment]
[v0.11 has now finally been released](https://github.com/troglobit/mdnsd/releases/tag/v0.11), initial integration and testing is being done in [myLinux](https://github.com/troglobit/myLinux/) (a Buildroot external tree), before I try to get it into Buildroot for the next LTS release.

**Comment by troglobit** [comment]
Submitted to Buildroot

https://lore.kernel.org/buildroot/20230123055259.2285749-1-troglobit@gmail.com/
